login:
  url:
    path: /users/login
server:
  port: ${port:0}
spring:
  application:
    name: UMS-USERS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: qshd bgwz wurs pivv
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: vaishnavdev05@gmail.com
token:
  expiration_time: 864000000
  secret: hgsd75767sdj87sd708bjh65
